/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.akainth.tape

import org.gradle.testkit.runner.GradleRunner
import java.io.File
import kotlin.test.Test

/**
 * A simple functional test for the 'me.akainth.tape.greeting' plugin.
 */
class TapePluginFunctionalTest {
    @Test
    fun `can run task`() {
        // Setup the test build
        val projectDir = File("build/functionalTest")
        projectDir.mkdirs()
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText("""
            plugins {
                id("me.akainth.tape")
            }
            
            tape {
                targetDirectory = file("../../src/functionalTest/kotlin/")
                def length = dimension("Length", "m") {
                    unit("ft", 0.3048)
                    unit("in", 39.3700787)
                    addMetricUnits()
                }
                def time = dimension("Time", "s") {
                    milli()
                    nano()
                }
                def speed = dimension("Speed", length / time)
                dimension("Acceleration", speed / time)
            }
        """.trimIndent())

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("tape")
        runner.withProjectDir(projectDir)
        runner.build()
    }
}
