/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.akainth.tape

import org.gradle.api.Action
import org.gradle.api.Project
import org.gradle.api.Plugin

class TapePlugin : Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
        project.pluginManager.apply("java")
        project.tasks.register("tape", GenerateDimensionsTask::class.java)

        project.tasks.getByName("tape") {
            (it as GenerateDimensionsTask).apply {
//                dimension("Length", "m", Action {
//                    it.unit("ft", 3.2808)
//                    it.unit("in", 39.3701)
//                    it.commonMetricVariants()
//                })
//                dimension("Time", "s", Action {
//                    it.milli()
//                    it.nano()
//                    it.micro()
//                })
                dimension("Mass", "g", Action {
                    it.kilo()
                })
            }
        }
    }
}
