/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.akainth.tape

import java.io.File
import org.gradle.testkit.runner.GradleRunner
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'me.akainth.tape.greeting' plugin.
 */
class TapePluginFunctionalTest {
    @Test
    fun `can run task`() {
        // Setup the test build
        val projectDir = File("build/functionalTest")
        projectDir.mkdirs()
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText(
            """
            plugins {
                id('me.akainth.tape')
                id("org.jetbrains.kotlin.jvm") version "1.3.72"
            }
            
            repositories {
                jcenter()
            }
            
            tape {
            
            }
            
            sourceSets {
                main {
                    java.srcDirs += tape.targetDirectory
                }
            }
            
            dependencies {
                implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
            }       
            compileJava.dependsOn(tape)           
            compileKotlin.dependsOn(tape)
            
            """.trimIndent()
        )

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("compileKotlin")
        runner.withProjectDir(projectDir)
        val result = runner.build();

        println(result)
    }
}
